overtrue/easy-sms

src/EasySms.php

@overtrue requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/overtrue/easy-sms/

Scrutinizer Auto-Fixes

---

README.md
src/Gateways/LuosimaoGateway.php
tests/Gateways/LuosimaoGatewayTest.php

新增服务商 Luosimao
调用示例
```php
$config = [
'gateways' => [
'luosimao' => [
'app_key' => 'xxxxxxxxxxxx',
],
],
];
$easySms = new EasySms($config);
$response = $easySms->gateway('luosimao')->send(18188888888, '测试信息【测试】');
```

Add Luosimao

---

README.md
src/Gateways/BaiduGateway.php
tests/Gateways/BaiduGatewayTest.php

优化阿里大于短信参数配置

---

README.md
src/Gateways/AliyunGateway.php
tests/Gateways/AlidayuGatewayTest.php
tests/Gateways/AliyunGatewayTest.php

#13 新增阿里云（AliyunGateway）短信发送API(SendSms)
https://help.aliyun.com/document_detail/55451.html

增加阿里云短信API发送通道

---

src/Gateways/AlidayuGateway.php
src/Traits/HasHttpRequest.php

- Fix alidayu parse the response body bug
- The repair send gateway is not injected into the message

Fix alidayu parse the response body bug

---

src/Gateways/AlidayuGateway.php

阿里大鱼部分情况返回值是这样的
```
array:1 [
"error_response" => array:3 [
"code" => 28
"msg" => "Missing app key"
"request_id" => "re9lsd2skvkh"
]
]
```
不进行修改则会这样
`Undefined index: sub_msg`

修复阿里大鱼网关错误信息问题

---

README.md
src/Gateways/ChuanglanGateway.php

增加253云通讯（创蓝）API接口

---

src/Gateways/RongcloudGateway.php

Rongcloud add send notify support

---

README.md

Fix issue 63

---

src/Contracts/GatewayInterface.php
src/Gateways/AlidayuGateway.php
src/Gateways/AliyunGateway.php
src/Gateways/BaiduGateway.php
src/Gateways/ChuanglanGateway.php
src/Gateways/ErrorlogGateway.php
src/Gateways/Gateway.php
src/Gateways/HuaxinGateway.php
src/Gateways/HuyiGateway.php
src/Gateways/JuheGateway.php
src/Gateways/LuosimaoGateway.php
src/Gateways/RongcloudGateway.php
src/Gateways/SendcloudGateway.php
src/Gateways/SubmailGateway.php
src/Gateways/YunpianGateway.php
src/Gateways/YuntongxunGateway.php
tests/EasySmsTest.php
tests/Gateways/AlidayuGatewayTest.php
tests/Gateways/AliyunGatewayTest.php
tests/Gateways/BaiduGatewayTest.php
tests/Gateways/HuaxinGatewayTest.php
tests/Gateways/HuyiGatewayTest.php
tests/Gateways/JuheGatewayTest.php
tests/Gateways/LuosimaoGatewayTest.php
tests/Gateways/SendcloudGatewayTest.php
tests/Gateways/SubmailGatewayTest.php
tests/Gateways/YunpianGatewayTest.php
tests/Gateways/YuntongxunGatewayTest.php

add getName to each gateway.
#69

add method to get gateway name

---

README.md
src/Gateways/TianyiwuxianGateway.php

Add tianyiwuxian support

---

src/Gateways/QcloudGateway.php

Fix code style

---

README.md
src/Gateways/AliyunrestGateway.php
tests/Gateways/AliyunrestGatewayTest.php

原有阿里云gateway不工作了，添加了新的基于阿里云rest gateway

添加了基于aliyun rest gateway

---

src/Gateways/SendcloudGateway.php

Revert "Update SendcloudGateway.php"

---

src/Gateways/AliyunrestGateway.php
src/Message.php

fix: 修复无法通过闭包获取data数据

---

src/Gateways/QcloudGateway.php

加入文本发送短信时为加签名自动读取默认签名

---

src/EasySms.php
tests/EasySmsTest.php

修复 GuzzleHttp\Client 超时时间设置问题

---

README.md
src/Gateways/UcloudGateway.php
tests/Gateways/UcloudGatewayTest.php

添加 Ucloud 短信

---

src/Gateways/Gateway.php
src/Traits/HasHttpRequest.php

config 中获取 options 作为 guzzle 配置选项

增加 Guzzle 选项配置

---

src/Gateways/YunpianGateway.php

YunPian support single_send and tpl_single_send

---

src/Gateways/QcloudGateway.php

修复腾讯云使用区号发送时，丢失手机号码参数的问题 #314
已经在本地测试了

修复腾讯云使用区号发送时，丢失手机号码参数的问题 #314

---

README.md
src/Gateways/AliyunIntlGateway.php
tests/Gateways/AliyunIntlGatewayTest.php

添加阿里云国际短信发送网关

---

README.md
src/Gateways/VolcengineGateway.php
tests/Gateways/VolcengineGatewayTest.php

添加字节跳动火山引擎短信服务支持

---

src/Gateways/UcloudGateway.php
tests/Gateways/UcloudGatewayTest.php

Ucloud网关支持模板指定签名

---

src/Gateways/Ue35Gateway.php

ue35 接口api路径变更

---

src/Contracts/MessageInterface.php
src/Contracts/PhoneNumberInterface.php
src/EasySms.php
src/Gateways/CtyunGateway.php
src/Gateways/ErrorlogGateway.php
src/Gateways/Ue35Gateway.php
src/Message.php
src/Messenger.php
src/PhoneNumber.php
src/Strategies/OrderStrategy.php
src/Strategies/RandomStrategy.php
src/Support/Config.php
tests/EasySmsTest.php
tests/Gateways/CtyunGatewayTest.php
tests/Gateways/ErrorlogGatewayTest.php

1. To update the method for generating random
2. Support for 8.4 nullable parameter
3. Update test cases
Closes #367

fix: update the method for generating random

---

README.md
src/Gateways/WeiqucloudGateway.php
tests/Gateways/WeiqucloudGatewayTest.php

增加 微趣云 短信发送渠道
各大服务商短信服务哑火的时候，这个小平台报备只要3-5天，有点神奇

增加 微趣云 短信发送渠道

---

README.md
src/Gateways/WeiqucloudGateway.php
tests/Gateways/WeiqucloudGatewayTest.php

完善 发送成功 逻辑判断
